### ISSUE TITLE
[request] Replace white background during app banner loading with something less bright and intensive

### ISSUE THREAD

**Issue by Baricanac** [sleeyax/pms-android#7]
When starting up the PMS-Android app, the app might take a while to load during the initial startup. Hence the white background with the banner becomes very bright and intensive to the human eye during the night as the loading sometimes might take up to 30+ seconds...

**Comment by sleeyax** [comment]
If it's the PMS loading screen that's too bright for you, a patch should probably be applied to PimpMyStremio itself and not the android version in particular.

**Comment by sleeyax** [comment]
PMS actually does support a dark theme (see settings after load). The loading screen should reflect the color of the configured theme.

Closing this because it's a PMS specific issue.
